import AppKit
import Testing
@testable import Selected

@MainActor
struct ClipDataTests {
    @Test func emptyPasteboardProducesAnEmptySnapshot() throws {
        let pasteboard = NSPasteboard.withUniqueName()
        defer { pasteboard.releaseGlobally() }
        let clip = try #require(ClipData(pasteboard: pasteboard))
        #expect(clip.types.isEmpty)
        #expect(clip.items.isEmpty)
        #expect(clip.plainText == nil)
        #expect(clip.url == nil)
        #expect(clip.ocrImage == nil)
    }

    @Test func supportedRepresentationsKeepTheirOrderAndOriginalBytes() throws {
        let pasteboard = NSPasteboard.withUniqueName()
        defer { pasteboard.releaseGlobally() }
        let source = NSPasteboard.PasteboardType("org.chromium.source-url")
        let unsupported = NSPasteboard.PasteboardType("selected.test.unsupported")
        let representations: [(NSPasteboard.PasteboardType, String)] = [
            (.string, "  原始文本\n"), (unsupported, "ignored"),
            (.html, "<b>原始文本</b>"), (source, "https://example.test/source")
        ]
        pasteboard.declareTypes(representations.map(\.0), owner: nil)
        for (type, value) in representations { pasteboard.setString(value, forType: type) }

        let clip = try #require(ClipData(pasteboard: pasteboard))
        #expect(clip.types == [.string, .html, source])
        #expect(clip.items.map(\.type) == clip.types)
        #expect(clip.items.map(\.data) == representations.filter { $0.0 != unsupported }.map { Data($0.1.utf8) })
        #expect(clip.plainText == "  原始文本\n")
        #expect(clip.url == "https://example.test/source")
    }

    @Test(arguments: ["org.nspasteboard.TransientType", "org.nspasteboard.ConcealedType",
                      "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword",
                      "com.typeit4me.clipping", "de.petermaurer.TransientPasteboardType", "net.antelle.keeweb"])
    func excludedRepresentationsRejectTheWholeSnapshot(_ rawType: String) {
        let pasteboard = NSPasteboard.withUniqueName()
        defer { pasteboard.releaseGlobally() }
        let excluded = NSPasteboard.PasteboardType(rawType)
        pasteboard.declareTypes([.string, excluded], owner: nil)
        pasteboard.setString("private text", forType: .string)
        pasteboard.setData(Data(), forType: excluded)
        #expect(ClipData(pasteboard: pasteboard) == nil)
    }

    @Test(arguments: [NSPasteboard.PasteboardType.html, .rtf])
    func richTextFirstRequiresAPlainTextRepresentation(_ type: NSPasteboard.PasteboardType) throws {
        let pasteboard = NSPasteboard.withUniqueName()
        defer { pasteboard.releaseGlobally() }
        pasteboard.declareTypes([type], owner: nil)
        pasteboard.setString("rich content", forType: type)
        #expect(ClipData(pasteboard: pasteboard) == nil)
        pasteboard.addTypes([.string], owner: nil)
        pasteboard.setString("", forType: .string)
        #expect(try #require(ClipData(pasteboard: pasteboard)).plainText == "")
    }

    @Test func laterURLRepresentationsKeepCurrentPrecedence() throws {
        let pasteboard = NSPasteboard.withUniqueName()
        defer { pasteboard.releaseGlobally() }
        let source = NSPasteboard.PasteboardType("org.chromium.source-url")
        pasteboard.declareTypes([.URL, .fileURL, source], owner: nil)
        pasteboard.setString("https://example.test/link", forType: .URL)
        pasteboard.setString("file:///tmp/example.txt", forType: .fileURL)
        pasteboard.setString("https://example.test/source", forType: source)
        let clip = try #require(ClipData(pasteboard: pasteboard))
        #expect(clip.url == "https://example.test/source")
        #expect(clip.items.count == 3)
        #expect(clip.plainText == nil)
    }

    @Test func invalidImageBytesArePreservedWithoutOCR() throws {
        let pasteboard = NSPasteboard.withUniqueName()
        defer { pasteboard.releaseGlobally() }
        let bytes = Data([0, 1, 2, 3])
        pasteboard.setData(bytes, forType: .png)
        let clip = try #require(ClipData(pasteboard: pasteboard))
        #expect(clip.items.first?.data == bytes)
        #expect(clip.ocrImage == nil)
    }

    @Test func colorSnapshotRemainsDecodableWithTheSameComponents() throws {
        let pasteboard = NSPasteboard.withUniqueName()
        defer { pasteboard.releaseGlobally() }
        let color = NSColor(srgbRed: 0.2, green: 0.4, blue: 0.6, alpha: 0.8)
        let encoded = colorToData(color: color)
        let bytes = try #require(encoded)
        pasteboard.setData(bytes, forType: .color)
        let clip = try #require(ClipData(pasteboard: pasteboard))
        let restored = try #require(clip.items.first.flatMap { decodeNSColor(from: $0.data) }?.usingColorSpace(.sRGB))
        #expect(abs(restored.redComponent - 0.2) < 0.001)
        #expect(abs(restored.greenComponent - 0.4) < 0.001)
        #expect(abs(restored.blueComponent - 0.6) < 0.001)
        #expect(abs(restored.alphaComponent - 0.8) < 0.001)
    }
}
