import AppKit

private let excludePasteboardTypes: Set<String> = [
    "org.nspasteboard.TransientType",
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.AutoGeneratedType",
    "com.agilebits.onepassword",
    "com.typeit4me.clipping",
    "de.petermaurer.TransientPasteboardType",
    "net.antelle.keeweb"]

private let SupportedPasteboardTypes: Set<NSPasteboard.PasteboardType> = [
    .URL,
    .color,
    .html,
    .pdf,
    .png,
    .rtf,
    .string,
    .fileURL,
    NSPasteboard.PasteboardType("org.chromium.source-url"),
    NSPasteboard.PasteboardType("NSColor pasteboard type"),
    .tiff
]

struct ClipData: Identifiable {
    var id: String
    var timeStamp: Int64
    var types: [NSPasteboard.PasteboardType]
    var appBundleID: String
    var items: [ClipItem]
    var ocrImage: NSImage? // if have any image

    var plainText: String? // maybe image ocr text
    var url: String?

    static private func filterPasteboardTypes(_ types: [NSPasteboard.PasteboardType]?) -> [NSPasteboard.PasteboardType] {
        guard let types = types else {
            return []
        }

        return types.filter { SupportedPasteboardTypes.contains($0) }
    }

    static private func shouldIgnore(_ types: [NSPasteboard.PasteboardType]?) -> Bool{
        guard let types = types else {
            return false
        }

        return types.contains { excludePasteboardTypes.contains($0.rawValue) }
    }

    init?(pasteboard: NSPasteboard) {
        self.id = UUID().uuidString
        self.timeStamp = Int64(Date().timeIntervalSince1970*1000)
        self.appBundleID = NSWorkspace.shared.frontmostApplication?.bundleIdentifier ?? "unknown"

        if ClipData.shouldIgnore(pasteboard.types) {
            return nil
        }

        self.types = ClipData.filterPasteboardTypes(pasteboard.types)

        var items = [ClipItem]()
        for type in types {
            guard var data = pasteboard.data(forType: type) else {
                continue
            }
            if type == .color || type.rawValue == "NSColor pasteboard type" {
                guard let color = decodeNSColor(from: data) else {
                    continue
                }
                if let tmpdata = colorToData(color: swiftUIColor(from: color)){
                    data = tmpdata
                } else {
                    continue
                }
            }

            let item = ClipItem(type: type, data: data)
            items.append(item)

            switch type {
                case .string:
                    if let content = pasteboard.string(forType: type) {
                        plainText = content
                    }
                case .init("org.chromium.source-url"), .fileURL, .URL:
                    if let content = pasteboard.string(forType: type) {
                        url = content
                    }
                case .png, .tiff:
                    if let image = NSImage(data: item.data) {
                        self.ocrImage = image
                        //                        self.plainText = recognizeTextInImage(image)
                    }
                default:
                    continue
            }
        }
        if (types.first == .html || types.first == .rtf ) && self.plainText == nil {
            return nil
        }
        self.items = items
    }
}

extension ClipData: Hashable {
    static func == (lhs: ClipData, rhs: ClipData) -> Bool {
        return lhs.timeStamp == rhs.timeStamp
    }

    func hash(into hasher: inout Hasher) {
        hasher.combine(timeStamp)
    }
}
